services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager-app
    ports:
      - "3000:3000"
    volumes:
      - app-data:/data
    restart: always

volumes:
  app-data:
    name: task-manager-data
